# Generated by Django 4.1.2 on 2022-12-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
